[package]
name = "diffui"
version = "0.1.0"
edition = "2024"

[features]
iced-debug = ["iced/debug"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
iced = { git = "https://github.com/iced-rs/iced.git", features = ["advanced", "tokio", "debug"] }
tokio = { version = "1.44", features = ["process", "time"] }

[profile.dev]
debug = 1

[profile.profiling]
inherits = "release"
debug = true
